@startuml mod03ima03
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
skinparam classAttributeIconSize 0 
class "janela" as o1
class "JanelaComVidro" as o2
class "Janela" as o3
class "Vidro" as o4
o1 : area 
o2 : areavidro 
o3 : area 
o4 : area
left to right direction
o1 <|--o2
o2 -[#White]- o3
o3 o-- "0..1"o4
@enduml
