@startuml mod07ima18
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

class "Aluno" as al
class "Computador" as co
left to right direction
al "0..1"---"1" co : UFG
al --- co : Casa
@enduml