@startuml mod05ima02
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "Teclado" as te
class "Computador" as co 
class "Placa-mãe" as pl
class "Mouse" as mo
class "Memória" as me
class "CPU" as cp
class "Dispositivo" as di
left to right direction
te --|> di
pl --|>di
cp --|>di
me --|>di
mo --|>di
di --o co
cp --o pl
cp --> me : Acessa
@enduml