@startuml mod02ima05
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "Usuário" as us
class "Pessoa" as pe
left to right direction
us --|> pe
@enduml