@startuml mod03ima05
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "Lanchonete" as la
class "Funcionário" as fu

left to right direction
la "emprega"----"2..* \n empregado" fu
la "0..1"-- "0..1 \n gerente"fu :Gerência
@enduml