@startuml mod01ima05

hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

class "País" as pa
class "Cidade" as ci
left to right direction
pa"1" o-- "*"ci: "Contém"
@enduml
