@startuml mod06ima03
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
skinparam LineType ortho

class "Jogador" as jo
class "Partida" as pa
class "Lance" as la
class "Peça" as pe
class "Posição" as po
class po {
    x
    y
}

jo <-down-"{Sequence}" la
pa *-right- la
la -right-> pe

la --> "destino" po 
la -down->"origem" po
@enduml