@startuml mod03ima06
allow_mixing
skinparam ClassAttributeIconSize 0
object "Prestação" as pr 
pr : - data
pr : - valor 
rectangle "Carnê" as ca 
rectangle "Compra" as co 
object "ItemCompra" as it 
it : - quantidade 
rectangle "Produto" as po
left to right direction
pr -left-* ca 
ca -- co
co *-- it
it "*"--"1" po
@enduml