@startuml mod01ima11
object "Permissão" as o1
object "Grupo" as o2
object "Usuário" as o3
object "Arquivo" as o4
left to right direction
o1"*" -- "1"o2: Permissão
o2 o-- o3
o4"1" -- "*"o1: Permissão
@enduml