@startuml mod07ima03
skinparam ClassAttributeIconSize 0
class "Círculo" as ci1
class ci1{
    - raio
    - x
    - y
    + move()
}
class "Círculo" as ci2
class ci2{
    - raio
    + move()
    }
class "Ponto" as po
class po{
    - x
    - y
    + move()
}
left to right direction
ci1 -[#White]- ci2
ci2 *--->"centro" po
@enduml