@startuml mod04ima06
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "Pilha" as pi 
class "Elemento" as el 

left to right direction
pi ----> "topo" el  
el "0..1 anterior"--> el
@enduml