@startuml mod07ima19
rectangle "Expressão" as ex
rectangle "Elemento" as el
rectangle "Operador" as op
rectangle "Operando" as on
left to right direction
ex "1"---"{ordered}" el
op -right-|> el
on -left-|> el
@enduml