@startuml mod01ima10
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
skinparam linetype ortho
class "Janela" as o1
class "Elemento de interação" as o2
class "Botão" as o3
class "Menu" as o4
class "Barra de rolagem" as o5
o3 -left-|> o2
o4 -right-|> o2
o5 -up-|> o2
left to right direction
o1 *-- o2
@enduml