@startuml mod05ima04
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
allow_mixing
skinparam classAttributeIconSize 0
class "Lanchonete" as la
class "Sanduíche" as sa
class "Garçonete" as ga
class "Pedido" as pe
class "Item" as it
class "Bebida" as be
class "Detalhe" as de 
de : descrição 
de : acompanhamento 

left to right direction
la --"*" sa : Serve
sa "0..1"-- it 
ga "1"--"*" pe : Coleta
pe o--it 
it --"0..1" be 
it "1"--"*" de
@enduml