@startuml mod07ima07
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "   A   " as a
class "   B   " as b
a <|-- b
a o-- b
@enduml