@startuml mod07ima01
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
skinparam Linetype ortho
class "Configuração cartas" as co
class "Carta" as ca
class "Jogador" as jo
class "MãoJogador" as mã
class "Monte" as mo
class "Rodada" as ro
co o-right- ca
mã -up-|> co
mo -up-|> co
jo -down- ro
(jo,ro) .. mã
ro --- mo
@enduml