@startuml mod07ima17
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

class "Linha" as li
class "Ponto" as po
class "Linha" as ln
class "Ponto" as pn
left to right direction
li "1"*-->"p2" po
li "1"*-->"p1" po
po -[#White]- ln
ln --->"2\n{ordered}" pn
@enduml