@startuml mod01ima02

hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

class "Projeto" as o1
class "Linguagem de programação" as o2

o1 - o2 : Faz uso 
@enduml
