@startuml mod01ima11
skinparam classAttributeIconSize 0
object "Pessoa" as o1
object "Emprego" as o2
object "Empresa" as o3
o1 : Empregado
o2 : -Salário \n -Início \n -Fim
left to right direction
o1"1" -- "*"o2: Permissão
o2"*" -- "1"o3
@enduml