@startuml
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

allow_mixing
skinparam ClassAttributeIconSize 0
class "Disco" as di
class "Arquivo" as ar
class "Usuário" as us
class "Permissão" as pe
pe : - leitura : Boolean
pe : - escrita : Boolean
pe : - execuão : Boolean
left to right direction
di *--> ar
ar -- us
(ar,us) .. pe
@enduml