@startuml mod07ima20 
rectangle "Associação" as ass
left to right direction
ass "para\n1"--- "    1\nde" ass : Relação
rectangle "Classe" as cl
left to right direction
cl "para"--- " \n de" cl : Associação
ass -[#White]- cl
@enduml