@startuml mod07ima20
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

class "Associação" as ass
left to right direction
ass "para\n1"--- "    1\nde" ass : Relação
class "Classe" as cl
left to right direction
cl "para"--- " \n de" cl : Associação
ass -[#White]- cl
@enduml