@startuml mod04ima01
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
allow_mixing
class "Array" as ar 
class "Elemento" as el 
left to right direction
ar"índice" ----> "elementos \n * \n {ordered}"el 
@enduml