@startuml mod06ima02
skinparam LineType ortho

object "Jogador" as jo
object "Partida" as pa
object "Lance" as la
object "Peça" as pe
object "Posição" as po

jo <-down- la
pa *-right- la
la -right-> pe

la --> "destino" po 
la -down->"origem" po
@enduml
