@startuml mod06ima02
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
skinparam LineType ortho

class "Jogador" as jo
class "Partida" as pa
class "Lance" as la
class "Peça" as pe
class "Posição" as po

jo <-down- la
pa *-right- la
la -right-> pe

la --> "destino" po 
la -down->"origem" po
@enduml
