@startuml mod03ima01
rectangle "Casa" as ca
rectangle "Quarto" as qu
rectangle "Banheiro" as ba
rectangle "Sala" as sa
rectangle "Garagem" as ga
rectangle "Área" as ar
ca o-down- qu
ca o-left- ba
ca o-right- sa
ca o-up- ga
ca o-- ar
@enduml