@startuml mod03ima01
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "Casa" as ca
class "Quarto" as qu
class "Banheiro" as ba
class "Sala" as sa
class "Garagem" as ga
class "Área" as ar
ca o-down- qu
ca o-left- ba
ca o-right- sa
ca o-up- ga
ca o-- ar
@enduml