@startuml mod07ima16
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

skinparam ClassAttributeIconSize 0
class "Calendário" as ca
ca : - ano
class "Evento" as ev
ev : -dia
ev : - descrição
left to right direction
ca o-down- ev : Feriado
ca o---> ev : Data importante
@enduml