@startuml mod03ima09
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "Período" as pe
class "Data" as da

left to right direction
da "1 \n final" ---- "*" pe
da "1 \n inicial" ---- "*" pe
@enduml