@startuml mod02ima10
skinparam classAttributeIconSize 0 
object "Cliente" as cl
object "Transação" as tr
object "Fornecedor" as fo
cl : - transações[] : Transação
tr : - cliente : Cliente
tr : - fornecedor : Fornecedor
fo : - transações[] : Transação
left to right direction
cl"1" --- "n"tr
tr"n" --- "1"fo
@enduml