@startuml mod02ima02
skinparam classAttributeIconSize 0
object "Pessoa" as pe
object "Hábito" as ha
pe : - nome \n - idade \n -hábitos
ha : -descrição \n -pessoa
left to right direction
pe"1" --- "n"ha
@enduml