@startuml mod05ima09
skinparam linetype ortho
object "Funcionário" as fu 
circle " " as p1
circle " " as p2
circle " " as p3
left to right direction

fu "gerente \n 0..1"-left- p1
p1 -down- p2
p2 -right- p3
p3 -up-" * \n gerenciado" fu
@enduml