@startuml
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "Funcionário" as fu 
left to right direction
fu "gerente \n 0..1"--- " * \n gerenciado" fu
@enduml