@startuml mod07ima12
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "Fila" as fi
class "Cliente" as cl
class "Fila" as fi2
class "Cliente" as cl2
left to right direction
fi o---> cl
cl -[#white]- fi2
fi2 o--->"{ordered}" cl2
@enduml