@startuml mod07ima14
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
left to right direction
class "cidade" as ci
class "Viagem" as vi
class "Papel" as pa
class "Passageiro" as ps
class "Ônibus" as on
class "Motorista" as mo
ci"destino" --- vi
ci "origem" --- vi
vi"n" --- "motorista\n1"pa
vi"n" --- "passageiros\nn"pa
pa <|-- ps
pa <|-right- mo
on --|> vi
@endtuml