@startuml mod03ima08
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
skinparam ClassAttributeIconSize 0
class "Preço" as pr 
pr : - valor 
pr : - moeda
@enduml