@startuml mod07ima15hide circle
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
skinparam ClassAttributeIconSize 0
class "Calendário" as ca
ca : - ano
class "Dia" as di
left to right direction
ca o-down- di : Feriado
ca o---> di : Data importante
@enduml
