@startuml mod0ima04
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "Grafo" as gr
class "Aresta" as ar
class "N?" as no

left to right direction
gr --->"umaAresta" ar
ar "*"----"1 \n origem" no
ar "*"--- "1 destino"no
@enduml