@startuml mod07ima14
left to right direction
object "cidade" as ci
object "Viagem" as vi
object "Papel" as pa
object "Passageiro" as ps
object "Ônibus" as on
object "Motorista" as mo
ci"destino" --- vi
ci "origem" --- vi
vi"n" --- "motorista\n1"pa
vi"n" --- "passageiros\nn"pa
pa <|-- ps
pa <|-right- mo
on --|> vi
@endtuml