@startuml mod07ima04
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

skinparam file {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
allowmixing
class "Pessoa" as pe
class "Usuário" as us
file "Associação" as ass
file "Herança" as he

pe -down- us
(pe,us) .left. ass
us -up-|> pe
(us,pe) .right. he
@enduml