@startuml mod04ima07
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "Lista duplamente \n encadeada" as li 
class "Elemento" as el 

left to right direction
li ----> "primeiro" el  
el "anterior 1"--- "1 próximo" el
li ---->"último" el
@enduml