@startuml
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

class "Diretor" as di
class "Funcionário" as fu
class "Docente" as do
class "Cargo" as ca
class "Pessoa" as pe
class "Vice-diretor" as vi
class "Aluno" as al
left to right direction
di -right-|> do
vi -left-|> do
do --|> ca
fu -right-|> ca
al -left-|> ca
ca <--"1" pe
@enduml