@startuml mod07ima05
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "Pessoa" as pe
class "Atividade" as at
class "Estudante" as es
class "Usuário" as us
left to right direction
pe--at
at<|--es
us--|>at
@enduml