@startuml mod05ima07
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "Trbalhador" as tr
class "Tarefa" as ta
class "Hora" as ho
class "Pagamento" as pa
class "Contrato" as co
class "Mensal" as me
left to right direction
tr -- ta : Desempenha
ta -right-"1" pa
ho --|> pa
co -up-|> pa
me -left-|> pa
@enduml