@startuml mod10ima01
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
skinparam ClassAttributeIconSize 0

class "Ocorrencia" as oc
class "Pessoa" as pe
class "Trabalhador" as tr
class "Funcionário" as fu
class "Venda" as ve
ve : - data
ve : - hora
class "Centro de Venda" as ce
class "Parque" as pa
class "Calendário" as ca
class "Data" as da
class "Visitante" as vi
class "Criança" as cr
class "Parente" as pr
class "Pai" as pi
class "Outro" as ou
class "Posto" as po
class "Polícia" as pl
class "Justiça" as ju
class "Escala" as es
class "Rádio" as rd
class "Bilhete" as bi
class "TocaAporB" as to
to : - data
to : - hora
to : - diferença




oc "*"--"1..*" pe : Envolve
pe "1"--"0..1" tr
tr <|--- fu
fu "1"--"*" ve
ve "*"--"1" ce
pa o-right-"*" pe : Direção
ca -- pa
ca -right->"*"da : Aberto em
pe "1"-right-"0..1"vi : ____  
cr --|> vi
cr "*"--"acompanhante *"vi
vi <|-- pr
pr <|-- pi
pr <|-right- ou 
po o-right- tr
ju -right-|> tr
(ju,tr)--pl
fu "1"-right-"*"es : ____  
es "1"-right-"*"rd : ____  
bi "*"-right-"1"ve
bi "a"-- to
bi "b"--to
to "*"-right-"1"ce
@enduml