@startuml mod04ima03-01
skinparam linetype ortho
object "Árvore" as ar 
object "Elemento" as el 
circle " " as p1
circle " " as p2
circle " " as p3

left to right direction
ar -->"0..1 \n raíz" el
el "filho 0..1"-left- p1
p1 -down- p2
p2 -right- p3
p3 -up-"0..1 \n pai" el

@enduml

