@startuml mod05ima08
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
skinparam ClassAttributeIconSize 0
class "Pessoa" as pe
class "Automóvel" as au
au : marca
au : modelo
au : ano
note "Naturalmente um\ncarro é dirigido por uma\núnica pessoa por vez." as na
left to right direction
pe "*"--"*" au : Dirige
(pe,au) .. na
@enduml