@startuml mod02ima01
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "Pessoa" as pe
class "Hábito" as ha
left to right direction
pe"1" --- "n"ha
@enduml