@startuml mod06ima01
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "Partida" as pa
class "Tabuleiro" as ta
left to right direction
pa o--> ta 
@enduml