@startuml mod07ima26
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

allow_mixing
class "Mensagem" as me
class "Objeto" as ob
left to right direction
ob "para"---"de" ob
(ob,ob) .. me
@enduml