@startuml mod01ima06

hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

skinparam SequenceMessageAlignment true
class "País" as pa
class "Cidade" as ci
left to right direction
pa"0...1"---"1 \n capital"ci: "Capital"
@enduml
