@startuml mod02ima09
object "Caixeiro-viajante" as ca
object "Viagem" as vi
object "Cidade" as ci
object "Armazém" as ar
object "Lista de pedidos" as li
left to right direction
ca"1" --- "*"vi
vi"*" --- " * \n {ordered}"ci : Percorre
ci"1" --- "*"ar : Possui
vi"1" --- "*"li
li"*" --- "1"ar
@enduml