@startuml mod04ima02 
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "Árvore" as ar 
class "Elemento" as el 

left to right direction
ar ----> "1 \n" el  
el "ancestral \n 0..1"--- " * \n descendentes" el
@enduml