@startuml mod05ima06
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "Professor" as pr
class "Trabalhador" as tr
class "Profissão" as po
class "Advogado" as ad
class "Açougueiro" as aç
class "Padeiro" as pa

pr -down-|> po
po -left--o tr : Desempenha
ad -left-|> po
pa -up-|> po
aç -up-|> po


@enduml