@startuml mod05ima12
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "Avaliação" as av
class "Questão" as qu
class "Aluno" as al
class "Prova" as pr
class "Resposta" as re
left to right direction
av o-->"1..*"qu
av "1"--"*" pr
al "1"--"*" pr
pr "1"*-->"1..*"re
@enduml