@startuml mod05ima11
skinparam ClassAttributeIconSize 0
object "Nota Fiscal" as no
object "Item" as it
it : - quantidade
it : - preçoUnitário
object "Produto" as pr
left to right direction
no *-- it
it -- pr 
@enduml