@startuml mod05ima11
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
skinparam ClassAttributeIconSize 0
class "Nota Fiscal" as no
class "Item" as it
it : - quantidade
it : - preçoUnitário
class "Produto" as pr
left to right direction
no *-- it
it -- pr 
@enduml