@startuml mod01ima04



skinparam object {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}


object "Texto" as o1
object "Parágrafo" as o2
object "Sentença" as o3
left to right direction
o1 o-- o2 
o2 o-- o3
@enduml
