@startuml mod01ima04
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
skinparam nodesep 5
class "Texto" as o1
class "Parágrafo" as o2
class "Sentença" as o3
left to right direction
o1 o-- o2 
o2 o-- o3
@enduml