@startuml mod03ima07
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
class "Frase" as fr
class "Palavra" as pa
class "Letra" as le

left to right direction
fr o---"1..* \n {ordered}"pa
pa o---"1..* \n {ordered}"le
@enduml
