@startuml mod05ima03
hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}
allow_mixing
skinparam classAttributeIconSize 0
class "Passageiro" as pa
pa : -bilhete
class "Lugar" as lu
class "Avião" as av
class "Aeroporto" as ae 
class "Operação" as op
op : -tipo 
op : -data 
op : -hora
class "Vôo" as vo
class "Piloto" as pi
class "Tripulação" as tr
class "Aeromoça" as aa
class "Co-piloto" as co
left to right direction

pa "0..1"--"1" lu
lu "*"<--* av
av "1"--"*" vo 
ae "1"--"*" op 
op "1"--"*" vo
pi --o tr
tr "1"--"1" vo
tr o-- aa
co --o tr

@enduml